# Generated by Django 3.2.5 on 2021-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permission2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permission3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permission4',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
