# Generated by Django 3.2.5 on 2021-08-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='submission_status',
            field=models.ForeignKey(default=1, max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.submission', verbose_name='Submission Status'),
        ),
    ]
