# Generated by Django 3.2.5 on 2021-08-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210801_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='SubmissionStatus',
        ),
    ]
