# Generated by Django 3.2.5 on 2021-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Submitted Project'),
        ),
    ]
