# Generated by Django 3.2.5 on 2021-08-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_team_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(choices=[('AI Developer', 'AI Developer'), ('AI Artist', 'AI Artist')], max_length=255, null=True, verbose_name='Speciality'),
        ),
    ]
